### ISSUE TITLE
It not works in android version.

### ISSUE THREAD

**Issue by umbrahan** [ColerYu/ANE-UMAnalytics#1]
Hi, ColerYu

I had made a review to ANE sample code.
All function calls are leading with "if (inIOS)";

I think this will not work on android. but U declared this ANE has supported Andoid;

Is there any hints u can give me?

Any help should be approaciated. Thanks.
my email: umbrahan@gmail.com

**Comment by ColerYu** [comment]
Hi,umbrahan
I updated the code on github,I fixed some issues on android.
And to test the event records,you need to stop the app,and run it again, the last  event records will be send to server.and you can see the report in a few minutes.

------------------ 原始邮件 ------------------
发件人: "umbrahan"notifications@github.com;
发送时间: 2013年8月28日(星期三) 晚上10:25
收件人: "ColerYu/ANE-UMAnalytics"ANE-UMAnalytics@noreply.github.com; 

主题: [ANE-UMAnalytics] It not works in android version. (#1)

Hi, ColerYu

I had made a review to ANE sample code.
 All function calls are leading with "if (inIOS)";

I think this will not work on android. but U declared this ANE has supported Andoid;

Is there any hints u can give me?

Any help should be approaciated. Thanks.
 my email: umbrahan@gmail.com
